<?php $as_rp=true; ?>

            <div class="as_ui_tab_content">
                <div class="as_ui_tab_title">Font Changer Usage:</div>
								<?php
								if($as_rp!==true):
								  echo 'Please purchase a license to unlock this feature';
								else:
								   echo ' Simply add shortcode <b class="shortcode">[asfont]</b> to any Post, Page, or Widget';
								endif;
								?>
            </div>
