<?php ?>
<ul class="ui-tabs-nav">
    <li id="li_contrast">
        <a href="#contrast">
            <div class="icon contrast-icon" id="as_contrast">Contrast Changer</div>
        </a>
    </li>
    <li id="li_fontchanger">
        <a href="#font-changer">
            <div class="icon font-changer-icon" id="as_fontchanger">Font Changer</div>
        </a>
    </li>
    <li id="li_skipnav">
        <a href="#skip-nav">
            <div class="icon skip-nav-icon" id="as_skipnav">Skip Navigation</div>
        </a>
    </li>
    <li id="li_textonly">
        <a href="#text-only">
            <div class="icon text-only-icon" id="as_textonly">Text Only</div>
        </a>
    </li>
<!--    <li id="li_transcript">
        <a href="#transcript">
            <div class="icon transcript-icon" id="as_transcript">Transcripts</div>
        </a>
    </li>

   <li id="li_license">
        <a href="#licensing">
            <div class="icon licensing-icon" id="as_license">Licensing</div>
        </a>
    </li>-->
</ul>
